#!/bin/bash
set -euo pipefail

############################################################
# Filter Mutect2 VCF for PhyloWGS input + run PhyloWGS
############################################################

CASE_ID="Case01"

# repo root = one level above this script's directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

OUTDIR="$REPO_ROOT/output/phylowgs/${CASE_ID}"
mkdir -p "$OUTDIR"

# Input VCF (generalized)
INPUT_VCF="/PATH/TO/WGS_${CASE_ID}.filt.vcf.gz"

# Tools
PHILOWGS_PARSER="/PATH/TO/phylowgs/parser/create_phylowgs_inputs.py"
PHILOWGS_RUN="/PATH/TO/phylowgs/multievolve.py"
WRITE_RESULTS="/PATH/TO/phylowgs/write_results.py"

# CNV tsv should be generated by script/01 and placed under OUTDIR (recommended)
CNV="${OUTDIR}/${CASE_ID}_CNV_phylowgs.tsv"

# -----------------------------
# Run everything inside OUTDIR
# -----------------------------
pushd "$OUTDIR" >/dev/null

# 1) Filter VCF (output stays in OUTDIR)
OUTPUT_VCF="${CASE_ID}.filtered.phylowgs.vcf"
bcftools view \
  -i 'INFO/TLOD > 10 && INFO/NLOD > 3 && INFO/DP >= 50' \
  "$INPUT_VCF" \
  > "$OUTPUT_VCF"

# 2) Create PhyloWGS input files (creates ./input/* relative to OUTDIR)
python2 "$PHILOWGS_PARSER" \
  --cnvs "${CASE_ID}=${CNV}" \
  --vcf-type "${CASE_ID}=mutect_smchet" \
  "${CASE_ID}=${OUTPUT_VCF}" \
  --tumor-sample "${CASE_ID}"

# 3) Run PhyloWGS (creates ./chains/* relative to OUTDIR)
python2 "$PHILOWGS_RUN" \
  --num-chains 16 \
  --ssms ./input/ssm_data.txt \
  --cnvs ./input/cnv_data.txt \
  --burnin-samples 500 \
  --mcmc-samples 2000

# 4) Summarize results (outputs in OUTDIR)
python2 "$WRITE_RESULTS" \
  "$CASE_ID" \
  ./chains/trees.zip \
  "${CASE_ID}.summary.json.gz" \
  "${CASE_ID}.mutations.json.gz" \
  "${CASE_ID}.mutass.zip"

popd >/dev/null




