#!/bin/bash
set -euo pipefail

############################################################
# 02_cnv_facets.sh
#
# Allele-specific copy number analysis using FACETS
#
# Input:
#   - Tumor BAM  : wgs_case01_tumor_L002_bqsr.bam
#   - Normal BAM : wgs_case01_normal_L002_bqsr.bam
#
# Output:
#   FACETS results (segmentation, purity/ploidy estimates)
#
# Sample ID: Case01
############################################################

# ==========================
# Paths (EDIT BEFORE RUN)
# ==========================
BASE_DIR="/PATH/TO/wgs_processing"

DATA_DIR="${BASE_DIR}/data"
OUT_DIR="${BASE_DIR}/output"

# References / annotations
REF_FASTA="${DATA_DIR}/Homo_sapiens_assembly38.fasta"
KNOWN_SITES_VCF="${DATA_DIR}/dbsnp138.hg38.vcf.gz"   # bgzip+tabix indexed
GENE_BED="${DATA_DIR}/hg38_gene.bed"

# ==========================
# Sample (EDIT)
# ==========================
SAMPLE_NAME="Case01"
SAMPLE_ID="case01"
LANE="L002"

# BAMs generated by 01_gatk_bwa_hg38.sh
TUMOR_PREFIX="wgs_${SAMPLE_ID}_tumor_${LANE}"
NORMAL_PREFIX="wgs_${SAMPLE_ID}_normal_${LANE}"

TUMOR_BAM="${OUT_DIR}/${TUMOR_PREFIX}_bqsr.bam"
NORMAL_BAM="${OUT_DIR}/${NORMAL_PREFIX}_bqsr.bam"

# ==========================
# Output
# ==========================
FACETS_DIR="${OUT_DIR}/facets/${SAMPLE_NAME}"
mkdir -p "$FACETS_DIR"

# ==========================
# Run FACETS
# ==========================
cnv_facets.R \
  -t "$TUMOR_BAM" \
  -n "$NORMAL_BAM" \
  -vcf "$KNOWN_SITES" \
  --annotation "$GENE_BED" \
  -o "${OUT_DIR}/${SAMPLE_NAME}"
