#!/bin/bash
set -euo pipefail

############################################################
# 03_mutect2.sh
#
# Somatic variant calling using GATK Mutect2
# + FilterMutectCalls
#
# Input:
#   - Tumor BAM  : wgs_case01_tumor_L002_bqsr.bam
#   - Normal BAM : wgs_case01_normal_L002_bqsr.bam
#
# Output:
#   WGS_Case01.filt.vcf.gz
#
# Reference: hg38
# Sample name (SM tag): Case01
############################################################

# ==========================
# Paths (EDIT BEFORE RUN)
# ==========================
BASE_DIR="/PATH/TO/wgs_processing"

DATA_DIR="${BASE_DIR}/data"
OUT_DIR="${BASE_DIR}/output"

REF_FASTA="${DATA_DIR}/Homo_sapiens_assembly38.fasta"
GERMLINE_RESOURCE="${DATA_DIR}/af-only-gnomad.hg38.vcf.gz"   # bgzip+tabix indexed

# ==========================
# Sample (EDIT)
# ==========================
SAMPLE_NAME="Case01"
SAMPLE_ID="case01"
LANE="L002"

# BAMs generated by 01_gatk_bwa_hg38.sh
TUMOR_PREFIX="wgs_${SAMPLE_ID}_tumor_${LANE}"
NORMAL_PREFIX="wgs_${SAMPLE_ID}_normal_${LANE}"

TUMOR_BAM="${OUT_DIR}/${TUMOR_PREFIX}_bqsr.bam"
NORMAL_BAM="${OUT_DIR}/${NORMAL_PREFIX}_bqsr.bam"

NORMAL_SM="${SAMPLE_NAME}_normal"   # e.g., Case01_normal

# ==========================
# Output
# ==========================
MUTECT2_DIR="${OUT_DIR}/mutect2/${SAMPLE_NAME}"
mkdir -p "$MUTECT2_DIR"

UNFILTERED_VCF="${MUTECT2_DIR}/${SAMPLE_NAME}.unfiltered.vcf.gz"
FILTERED_VCF="${MUTECT2_DIR}/WGS_${SAMPLE_NAME}.filt.vcf.gz"

# ==========================
# 1) Mutect2
# ==========================
gatk Mutect2 \
  -R "$REF_FASTA" \
  -I "$TUMOR_BAM" \
  -I "$NORMAL_BAM" \
  -normal "$NORMAL_SM" \
  --germline-resource "$GERMLINE_RESOURCE" \
  --native-pair-hmm-threads 24 \
  -O "$UNFILTERED_VCF"

# ==========================
# 2) FilterMutectCalls
# ==========================
gatk FilterMutectCalls \
  -R "$REF_FASTA" \
  -V "$UNFILTERED_VCF" \
  -O "$FILTERED_VCF"

# ==========================
# 3) Index
# ==========================
tabix -p vcf "$FILTERED_VCF"

echo "Mutect2 + filtering completed for ${SAMPLE_NAME}"
