#!/usr/bin/env python3

############################################################
# 02_sc_cnv_correlation.py
#
# Correlate inferCNV-derived iCNV (cell-group level) with
# WGS-derived mTCN (FACETS) over Segmented_Chr windows.
#
# Inputs:
#   - iCNV matrix (cell-group x Segmented_Chr):
#       ../data/iCNV.HMM_SegmentedChr_<CASE>.csv
#   - WGS mTCN over Segmented_Chr:
#       ../output/facetTCN_SegmentedChr_<WGS_SAMPLE>.tsv
#   - Cell-to-cell_group annotation (inferCNV output; TSV):
#       (path set below; generalized)
#
# Outputs:
#   - ../output/sc-iCNV.Corr_<CASE>.csv
#   - ../output/iCNV.HMM_SegmentedChr_sc_<CASE>.csv
############################################################

from pathlib import Path
import pandas as pd


def main():
    script_dir = Path(__file__).resolve().parent
    base_dir = script_dir.parent  # cnv_integration/

    # -----------------------------
    # Paths (EDIT BEFORE RUN)
    # -----------------------------
    # inferCNV result root (contains per-case subdirectories)
    INFERCNV_DIR = Path("/PATH/TO/inferCNV_results")

    # Case mapping: analysis case -> WGS sample name used in FACETS output
    dict_sm_wgs = {
        "Case01": "Case01_T"
    }

    data_dir = base_dir / "data"
    out_dir = base_dir / "output"
    out_dir.mkdir(parents=True, exist_ok=True)

    for sm, sm_wgs in dict_sm_wgs.items():
        print("Case:", sm)

        # iCNV (cell-group level), generated upstream (expected in data/)
        in_icnv = data_dir / f"iCNV.HMM_SegmentedChr_{sm}.csv"

        # WGS segmented mTCN, generated by 01_segment_cnv.py (expected in output/)
        # NOTE: 01_segment_cnv.py in the revised version outputs TSV.
        in_mTCN = out_dir / f"facetTCN_SegmentedChr_{sm_wgs}.csv"

        # inferCNV cell grouping table (tab-delimited)
        in_ann = INFERCNV_DIR / sm / "17_HMM_predHMMi6.leiden.hmm_mode-subclusters.cell_groupings"

        out_corr = out_dir / f"sc-iCNV.Corr_{sm}.csv"
        out_sc_icnv = out_dir / f"iCNV.HMM_SegmentedChr_sc_{sm}.csv"

        # -----------------------------
        # Read inputs
        # -----------------------------
        d_iCNV = pd.read_csv(in_icnv).set_index("Segmented_Chr")

        # facetTCN file is TSV in the revised pipeline
        d_mTCN = pd.read_csv(in_mTCN, sep="\t").set_index("Segmented_Chr")

        # cell_group_name index is required for merging
        cell_ann = pd.read_csv(in_ann, sep="\t").set_index("cell_group_name")

        # -----------------------------
        # Correlation: each cell-group iCNV profile vs WGS mTCN
        # -----------------------------
        corr_gp = d_iCNV.corrwith(d_mTCN["mTCN"])
        d_corr_gp = pd.DataFrame({"Corr": corr_gp})

        # Map correlation to single cells via cell_group_name
        d_corr_cell = pd.merge(cell_ann, d_corr_gp, left_index=True, right_index=True)
        d_corr_cell.to_csv(out_corr, index=False)
        print("Wrote:", out_corr)

        # -----------------------------
        # Expand to single-cell x Segmented_Chr matrix
        # -----------------------------
        d_sc_iCNV = pd.merge(cell_ann, d_iCNV.T, left_index=True, right_index=True)
        d_sc_iCNV.to_csv(out_sc_icnv, index=False)
        print("Wrote:", out_sc_icnv)


if __name__ == "__main__":
    main()

